# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e100376428c963ae430a1ea065da22ace7acefd152ad07039c001f5ac65e41066556c3f97135ca2d9f95e426ce489564fd83eff4d704298f097c3c8aebe15856

test:
  secret_key_base: 3837d82f13844b57fcbe722582d606c6243a82131d9b882e72d85530c7927edc7c4d658b20df51c40e22679af441571ce3dd08db700e24f47d851c3fca7b0d51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
